on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-test

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
              any::rcmdcheck
              any::devtools
          needs: check
          working-directory: ./R

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./R

      - run: Rscript -e 'library(devtools)'
      - run: Rscript -e 'devtools::install_github("chaisemartinPackages/twowayfeweights/R")'
      - run: Rscript -e 'library(TwoWayFEWeights)'
      - run: Rscript -e 'source("./R/inst/tinytest/test_wagepan.R")'

